library: /home/nicola/.config/beets/library.db 
directory: /srv/media/Music

plugins: [
#    beatport,
#    embyupdate,
#    chroma,
#    discogs,
    fetchart,
    embedart,
    zero,
    duplicates,
    permissions,
#    plexupdate,
    info,
    edit,
    inline,
    fromfilename,
    scrub,
#    lyrics,
#    web,
    replaygain ] 

import:
    write: yes
    copy: no
    move: yes
    resume: yes
    incremental: no
    quiet_fallback: asis
    none_rec_action: asis
    timid: no
    detail: yes
    log: beets.log
    autotag: yes
    default_action: apply
    group_albums: no
    duplicate_action: remove

web:
    host: 0.0.0.0
    port: 9999
    cors: '*'

duplicates:
    album: yes
    keys: [
         album,
         albumartist ]
    tiebreak: 
        items: [bitrate]
    strict: yes

va_name: 'Various Artists'
asciify_paths: yes
per_disc_numbering: yes

acoustid:
    apikey: XsoEays0uz

replace:
    '[\\/]': '-'
    '^\.': ''
    '[\x00-\x1f]': ''
    '[<>:"\?\*\|]': ''
    '\.$': ''
    '\s+$': ''
    '^\s+': ''
    '^-': ''
    '_': '-'

replaygain:
    auto: yes
    backend: gstreamer
    overwrite: no

permissions:
    file: 664
    dir: 775

emby:
    host: 192.168.178.13
    port: 8096
    username: Nicola
    apikey: af3ad32a5cbf4ea88d6e3e899a600097

plex:
    host: 192.168.178.13
    port: 32400
    token: MxkrUixVGKeu4244rdw8

zero:
    fields: disc disctotal track tracktotal original_year comments day month bpm
    disc: '^0$'
    disctotal: '^0$'
    track: '^0$'
    tracktotal: '^0$'
    original_year: '^0$'
    day: '^00$'
    month: '^00$'
    bpm: '^0$'
    update_database: true
    
musicbrainz:
    searchlimit: 5 

paths:
    comp: Various Artists/$album%aunique{}/%if{$multidisc,Disc $disc_nonpadded/}$track. $artist - $title
    default: $albumartist/$album%aunique{}/%if{$multidisc,Disc $disc_nonpadded/}$track. $artist - $title
    singleton: $artist/Non-Album/$artist - $title

item_fields:
    multidisc: 1 if disctotal > 1 else 0
    disc_nonpadded: disc

fetchart:
    cover_names: cover front art album folder
    minwidth: 300
    sources: filesystem google coverart itunes
    google_key: AIzaSyCUWgcRMPt7YIsOP-hh4EKyvxsxgdNx8N4
    google_engine: 008421613689071586690:eog2smafxhc
    enforce_ratio: yes

embedart:
    maxwidth: 600

match:
    strong_rec_thresh: 0.06
    medium_rec_thresh: 0.18
    required: artist
  
ui:
    color: yes
